var sealQuery = new SealInfoQuery();
sealQuery.initQuery(false);
var accInfo;// 账户信息
var accNo = null;
var accName = null;
var pointNo = null;
var accType = null;
var startDate = null;
var endDate = null;
var sort = null;
var searchType = null;

//初始加载页面时
var currentPage = 0; // 页索引
var accInfoList;// 表数据
var p = new parent.ParentAttrManager();//add by youlijun 2012-8-14

// 页面显示时的一些默认参数描述信息
var accFlags;
var accTypes;
var accAategorys;
var currencyTypes;
var withDrawFlags;
var attentionFlags;
var sealTypes;
var sealForms;
var loginPeopleInfo; // 登录人员信息
var currentLimitYear = 0;//当年库查询年限
var historyLimitYear = 0;//历史库查询年限
var sortTableList = new Array();//记录每列的点击次数，以便升降排序
function closeInfo(){
	$("#ui_sci_addcombine").attr("disabled",true);
	$("#accinfodiv").hide();
	if(p.getAttrWithAutoClear("querySealAccno")){
		history.back(1);
	}
}

//
/**
 * 账号规则检查
 * @returns {Boolean}
 */
checkAccnoInAccinfoSearche = function(){
	var input = $("#accNoInput").val();
	var ruleLen=getAccNoRule();
	var rules =getAccNoRuleReg(); 
	var tips=null;
	var rule=null;
	if(ruleLen){
		tips=ruleLen.toString();
	}
	if(tips){
		rule="/"
		for(var i=0;i<ruleLen.length;i++){
			if(rules){
				//2013-10-14修复bug:数据库中配置AccNoRule允许账户位数为1位时，系统表现为不生效
				if(ruleLen[i]==1){
					rule+="^[a-zA-Z0-9]$|";
				}else{
					rule+=rules.replace("$length",(parseInt(ruleLen[i])-2));
				}				
			}else{
				rule+="^[a-zA-Z0-9][a-zA-Z0-9\-]{"+(parseInt(ruleLen[i])-2)+"}[a-zA-Z0-9]$|"
			}
		}
		rule=rule.substring(0, rule.length-1);
		rule+="/";
	}
	if((input.trim()!="")&&rule && !(eval(rule)).test(input)){
		var tipMsg = $$.language.accinfo.accNoValidateTip;
		tipMsg = tipMsg.replace("{$length}",tips);
		if(confirm(tipMsg)){
			$("#accNoInput").select();
			$("#accNoInput").focus();
		}
	}
}

/*window.onresize=function()
{
	document.all.accinfodiv.style.width=document.body.clientWidth;   
	
	//屏蔽右键
//	document.oncontextmenu=function(){ 
//		event.returnValue=false ;
//	};
	
	//设置高度
//	if(document.body.scrollHeight > document.body.clientHeight)
//	{
//		document.all.accinfodiv.style.height=document.body.scrollHeight; 
//	}
//	else
//	{
//		document.all.accinfodiv.style.height=document.body.clientHeight; 
//	}
};*/
//TODO 将document隐藏
if(p.getAttrWithAutoClear("querySealAccno")){
	$(".frame").hide();
}
$(document).ready(function(){
	var pageInitAction = function(self){
		$.keyCodeReg(27,function(){
			if($(".frame").is(":visible")){//账户详细信息展开时，按ESC键关闭详细信息页面
				closeInfo();
			}
		});
	};
	
	var cleanAction = function(self){
		$(this).clearSealCard();
		$("#accInfoUI").accinfo("hideUreason");
	};
	
	
	//2013-11-04:解挂原由输入框
	$("#sealLossMsgBox").dialog({
		autoOpen: false,
		height: 270,
		width: 400,
		modal: true,
		resizable : false,
		buttons: {
			"确定": function() {
				$( this ).dialog( "close" );
			},
			/*"取消": function() {
				$( this ).dialog( "close" );
			}*/
		},
		open: function() {
			
		},
		close: function() {
			
		}
	});
	
	var accInfoInitAction = function(self){
		accInfo = self.accInfo;
		var sealMode = {
			lossRegister:{
				yes:{
					top1:'已挂失',
					img:'seal_gray_base64',
					bottom:{
						text:'印鉴 ',
						value: 'sealId'
					}
				},
				no:{
					img:'seal_white_base64',
					bottom:{
						text:'印鉴 ',
						value: 'sealId'
					}
				}
			},
			sealStatu:{
				cancel:{
					top1:'已注销',
					img:'seal_gray_base64',
					bottom:{
						text:'印鉴 ',
						value: 'sealId'
					}
				}
			}
		};
		self.accInfo.sealMode = sealMode;
		$(this).initSealCard(self.accInfo,self.autoModeling,self.ifDownload);
		$("#accInfoUI").accinfo("hideUreason");
	};
	
	$("#accInfoUI").accinfo({
		title: '账户信息',
		showTitle:true,
		accDivHeight:"220px",
		accDivContractionHeight:"62px",
		showType:0,//0,表示查询 1 表示录入 2 表示变更 3 表示审核  14表示资料复核
		operCode:"ACCINFO_QUERY",
		isTaskAssociated:false,
		accInfoInitAction:accInfoInitAction,//accinfo数据初始化之后回调方法
		cleanAction:cleanAction,//accinfo数据清空时回调方法
		pageInitAction:pageInitAction,//页面创建之后回调方法
		buttons : [ {
			text : '打印',
			id : 'printSealCardImage',
			callback : printSealCardImage
		} ]
	});
	
	$("#ui_sealCardInfo").sealCardInfo({
		width:330,			     
        height:400,	
		autoInit:false,
		simpleViewModel:true,
		autogeneratedID:false,
		curPageType:"QUERY"
	});
	$("#sealCardImage").sealCardImage({
		width:330,			     
        height:360,
		autoInit:false,
		showVideo:false,
		showProgressBar:true,
		imgAreaSelectEnable:false,
		simpleModel:true,
		curPageType:"QUERY"
	});
	$("#sealcombineUI").sealcombine({type:0});
	$("#ui_sealCardInfo").bind("sealcardinfo_addcombine", function(event,data){
		$("#sealcombineUI").sealcombine("open", accInfo);
	});
	
	initView();
	
	// 界面显示时将null用""替代
	function transNullToBlank(value){
		if (value == undefined || value == null || value == ""){
			return "&nbsp;";
		}
		return value;
	}
	
	//点击列名，根据列名进行排序
	$(".sort").click(function(){
		//获得对应td的列
		var colIndex = $(this).parent().find("td").index($(this)[0]);
		if(sortTableList[colIndex]==undefined){
			sortTableList[colIndex] = 1;
		}else{
			sortTableList[colIndex] = sortTableList[colIndex]+1;
		}
		if(parseInt(colIndex) == 0){
			numsort(sortTableList,colIndex,"accno");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 1){
			numsort(sortTableList,colIndex,"accName");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 2){
			numsort(sortTableList,colIndex,"accType");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 3){
			numsort(sortTableList,colIndex,"openDate");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 4){
			numsort(sortTableList,colIndex,"startDate");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 5){
			numsort(sortTableList,colIndex,"endDate");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 6){
			numsort(sortTableList,colIndex,"pointNo");
			createPage(accInfoList);
		}else if(parseInt(colIndex) == 7){
			numsort(sortTableList,colIndex,"accFlag");
			createPage(accInfoList);
		}
	});
	
	//进行排序
	function numsort(sortTableList,colIndex,name){
		if(sortTableList[colIndex]%2 == 1){
			for (var i = 0; i < accInfoList.length; i++) {
		        for (var j = (accInfoList.length - 1); j >i; j--) {
		            _n1 = accInfoList[i][name];
		            _n2 = accInfoList[j][name];
		            if (_n1 < _n2) {
		                temp = accInfoList[i];
		                accInfoList[i] = accInfoList[j];
		                accInfoList[j] = temp;
		            	}
		        	}
	    	}
			$("#descRadio").attr("checked",true);
		}else{
			for (var i = 0; i < accInfoList.length; i++) {
		        for (var j = (accInfoList.length - 1); j >i; j--) {
		        	 _n1 = accInfoList[i][name];
			         _n2 = accInfoList[j][name];
		            if (_n1 > _n2) {
		                temp = accInfoList[i];
		                accInfoList[i] = accInfoList[j];
		                accInfoList[j] = temp;
		            	}
		        	}
	    	}
//			$("#ascRadio").attr("checked",true);
		}
		$("#sortPropertySel").val(name);
	}
	
	//产生页面
	function createPage(sortTableList){
		//清空显示层中的数据
		$("#con_cont").html("");
		var str = "<table width='100%'  id='con_tab' cellpadding='0' cellspacing='0'>";
		$.each(sortTableList,function(i,value){
			var accNameTitle = transNullToBlank(value.accName).length>6?transNullToBlank(value.accName.substr(0,5))+"...":transNullToBlank(value.accName);
			var tempMainAccNo="";
			if(value.mainAccInfo){
				tempMainAccNo = value.mainAccInfo.accno;
			}
			if (i==0){
				str += "<tr class='tr_top trbg' ><td align='center'>"+transNullToBlank(value.accno)+"</td>" +
						"<td align='center'><font title='"+transNullToBlank(value.accName)+"'>"+accNameTitle+"</font></td>" +
						"<td align='center'>"+transNullToBlank(getParamMemo(value.accType,accTypes))+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.openDate)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.startDate)+"</td>"+
			       		"<td align='center'>"+transNullToBlank(value.endDate)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.pointNo)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(tempMainAccNo)+"</td>" +
			       		"<td style='border-right:none;' align='center'>"+transNullToBlank(getAccountFlag(value))+"</td></tr>";
			}else if((i+1)%2 == 0){
				str += "<tr class='tr_second trbg' col="+(i+1)+" ><td align='center'>"+transNullToBlank(value.accno)+"</td>" +
						"<td align='center'><font title='"+transNullToBlank(value.accName)+"'>"+accNameTitle+"</font></td>" +
						"<td align='center'>"+transNullToBlank(getParamMemo(value.accType,accTypes))+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.openDate)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.startDate)+"</td>"+
			       		"<td align='center'>"+transNullToBlank(value.endDate)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.pointNo)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(tempMainAccNo)+"</td>" +
			       		"<td style='border-right:none;' align='center'>"+transNullToBlank(getAccountFlag(value))+"</td></tr>";
			}else{
				str += "<tr class='tr_top1 trbg' col="+(i+1)+" ><td align='center'>"+transNullToBlank(value.accno)+"</td>" +
						"<td align='center'><font title='"+transNullToBlank(value.accName)+"'>"+accNameTitle+"</font></td>" +
						"<td align='center'>"+transNullToBlank(getParamMemo(value.accType,accTypes))+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.openDate)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.startDate)+"</td>"+
			       		"<td align='center'>"+transNullToBlank(value.endDate)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(value.pointNo)+"</td>" +
			       		"<td align='center'>"+transNullToBlank(tempMainAccNo)+"</td>" +
			       		"<td style='border-right:none;' align='center'>"+transNullToBlank(getAccountFlag(value))+"</td></tr>";
			}
		});
		$("#con_cont").html(str+"</table>");
	}
	
	//分页查询的事件响应代码
	$(function() {	
		// 跳转按钮click事件
		$("#jumpPageButton").click(function() {
			var totalPage = parseInt($("#totalPage").text());
			var jumpPage = parseInt($("#currentPage").val());
			if (isNaN(jumpPage) || jumpPage < 1 || jumpPage > totalPage){
				$("#currentPage").val(currentPage);
				return;
			}
			currentPage = jumpPage;
			$("#currentPage").val(currentPage);
			BindData(false);
		});
				
		// 第一页按钮click事件
		$("#first").click(function() {
			if (currentPage == 0 || currentPage == 1){
				return;
			}else{
				currentPage = 1;
			}
			$("#currentPage").val(currentPage);
			BindData(false);
		});
		
		// 上一页按钮click事件
		$("#previous").click(function() {
			if (currentPage == 0 || currentPage == 1){
				return;
			}else{
				currentPage--;
			}
			$("#currentPage").val(currentPage);
			BindData(false);
		});
		
		// 下一页按钮click事件
		$("#next").click(function() {
			var totalPage = parseInt($("#totalPage").text());
			if (currentPage == 0 || currentPage == totalPage){
				return;
			}else if (currentPage != totalPage) {
				currentPage++;
			}
			$("#currentPage").val(currentPage);
			BindData(false);
		});
		
		// 最后一页按钮click事件
		$("#last").click(function() {
			var totalPage = parseInt($("#totalPage").text());
			if (currentPage == 0 || currentPage == totalPage){
				return;
			}else{
				currentPage = totalPage;
			}
			$("#currentPage").val(currentPage);
			BindData(false);
		});
	});
	
	// 回车，查询数据 
	$.keyCodeReg(13,function(){
		currentPage = 0;
		BindData(true);
	});
	
	//向服务器发送表达数据并且接受服务端返回的数据显示
	$("#searchButton").click(function(){
		currentPage = 0;
		BindData(true);
	});
	
	$("#resetBtn").click(function(){
		$("#accNoInput").val("");
		$("#accNameInput").val("");
		$("#pointNoInput").val("");
		$("#accTypeSel").get(0).selectedIndex=0;
		$("#queryUnderPoint").val("1");
		initDate();
		$("#sortPropertySel").get(0).selectedIndex=0;
//		$("#ascRadio").attr("checked","checked");
	});
	
	$("#printBtn").click(function(){
		window.open("accSearchAction_PDF.action");
	});
	
	$("#explortBtn").click(function(){
		$("#explortDivHidden").html("");
		$("#explortDivHidden").append("<iframe id='exportHiddenIframe' style='display:none' ></iframe>");
		$("#explortDivHidden").append("<form id='exportForm' action='accSearch!exportExcel.action' target='exportHiddenIframe' method='post'>" +
				"<input type='hidden' name='accNoText' value='"+accNo+"' />" +
				"<input type='hidden' name='accNameText' value='"+accName+"' />" +
				"<input type='hidden' name='accPointText' value='"+pointNo+"' />" +
				"<input type='hidden' name='accTypeText' value='"+accType+"' />" + 
				"<input type='hidden' name='queryUnderPoint' value='"+queryUnderPointVal+"' />" +
				"<input type='hidden' name='startTimeText' value='"+startDate+"' />" +
				"<input type='hidden' name='endTimeText' value='"+endDate+"' />" +
				"<input type='hidden' name='searchTypeText' value='"+searchType+"' />" +
				"<input type='hidden' name='sortText' value='"+sort+"' />" +
				"<input type='hidden' name='databaseText' value='current' />" +
				"<input type='hidden' name='loginOrganNo' value='"+loginPeopleInfo.orgNo+"' />" +
				"</form>");
		$("#exportForm").submit();
	});
	
	// AJAX方法取得数据并显示到页面上
	function BindData(initalSign) {
		if(initalSign){//只有点击查询按钮进行查询时，会重新生成查询条件
			// 控制不允许输入全角字符
			accNo = noFullInput($("#accNoInput"));
			checkAccnoInAccinfoSearche();
			
			accName = noFullInput($("#accNameInput"));
			
			pointNo = noFullInput($("#pointNoInput"));
			
			startDate = $("#startTime").val();
			endDate = $("#endTime").val();
			accType = $("#accTypeSel").val();
			mainaccId = $("#mainaccId").val();
			
			queryUnderPointVal = $("#queryUnderPoint").val();
			
//			sort = $("#ascRadio").attr("checked")==undefined?"desc":"asc";
			searchType = $("#sortPropertySel").val();
			
			if (startDate != "" && $(this).isDate(startDate) == false){
				alert("开始时间格式错误,请重新输入");
				return;
			}
			
			if (endDate != "" && $(this).isDate(endDate) == false){
				alert("结束时间格式错误,请重新输入");
				return;
			}
			
			//如果起始时间和结束时间都有，那么起始时间不能大于结束时间
			if (startDate > endDate && endDate != ""){
				alert("开始时间不能晚于结束时间,请重新输入");
				return;
			}
			
			//如果起始时间有且在范围内，结束时间为空，结束时间为今天
			if (startDate !="" && endDate == ""){
				$("#endTime").val($.datepicker.formatDate("yy-mm-dd", new Date()));
			}
			
			if (loginPeopleInfo == undefined){
				loginPeopleInfo = getPeopleInfoObj();
			}
		}
		
		$.post("accSearch!queryPageInfo.action",
				{accNoText:accNo,
			accNameText:accName,
			accPointText:pointNo,
			accTypeText:accType,
			queryUnderPoint:queryUnderPointVal,
			startTimeText:startDate,
			endTimeText:endDate,
			searchTypeText:searchType,
			mainaccId:mainaccId,
			sortText:"asc",
			databaseText:"current",
			currentPage:currentPage,
			loginOrganNo:loginPeopleInfo.orgNo},
			function(data){
				if (currentPage == 0 && data.totalRows != 0){
					currentPage = 1;
				}
				$("#currentPage").text(currentPage);
				$("#totalNum").text(data.totalRows);
				$("#totalPage").text(data.totalPages);
				
				sortTableList = new Array();
				accInfoList = new Array();
//					alert("已经获取到数据： "+data.accInfoListStr.length+"  ,并开始生成表格数据");
				//清空显示层中的数据
				$("#con_cont").html("");
				var str = "<table width='100%'  id='con_tab' cellpadding='0' cellspacing='0'>";
				$.each(data.accInfoListStr,function(i,value){
					value = eval('('+value+')');
					accInfoList[i] = value;
					var accNameTitle = transNullToBlank(value.accName).length>6?transNullToBlank(value.accName.substr(0,5))+"...":transNullToBlank(value.accName);
					var tempMainAccNo="";
					if(value.mainAccInfo){
						tempMainAccNo = value.mainAccInfo.accno;
					}
					if (i==0){
						str += "<tr class='tr_top trbg' ><td align='center'>"+transNullToBlank(value.accno)+"</td>" +
						"<td align='center'><font title='"+transNullToBlank(value.accName)+"'>"+accNameTitle+"</font></td>" +
						"<td align='center'>"+transNullToBlank(getParamMemo(value.accType,accTypes))+"</td>" +
						"<td align='center'>"+transNullToBlank(value.openDate)+"</td>" +
						"<td align='center'>"+transNullToBlank(value.startDate)+"</td>"+
						"<td align='center'>"+transNullToBlank(value.endDate)+"</td>" +
						"<td align='center'>"+transNullToBlank(value.pointNo)+"</td>" +
						"<td align='center'>"+transNullToBlank(tempMainAccNo)+"</td>" +
						"<td style='border-right:none;' align='center'>"+transNullToBlank(getAccountFlag(value))+"</td></tr>";
					}else if((i+1)%2 == 0){
						str += "<tr class='tr_second trbg' col="+(i+1)+" ><td align='center'>"+transNullToBlank(value.accno)+"</td>" +
						"<td align='center'><font title='"+transNullToBlank(value.accName)+"'>"+accNameTitle+"</font></td>" +
						"<td align='center'>"+transNullToBlank(getParamMemo(value.accType,accTypes))+"</td>" +
						"<td align='center'>"+transNullToBlank(value.openDate)+"</td>" +
						"<td align='center'>"+transNullToBlank(value.startDate)+"</td>"+
						"<td align='center'>"+transNullToBlank(value.endDate)+"</td>" +
						"<td align='center'>"+transNullToBlank(value.pointNo)+"</td>" +
						"<td align='center'>"+transNullToBlank(tempMainAccNo)+"</td>" +
						"<td style='border-right:none;' align='center'>"+transNullToBlank(getAccountFlag(value))+"</td></tr>";
					}else{
						str += "<tr class='tr_top1 trbg' col="+(i+1)+" ><td align='center'>"+transNullToBlank(value.accno)+"</td>" +
						"<td align='center'><font title='"+transNullToBlank(value.accName)+"'>"+accNameTitle+"</font></td>" +
						"<td align='center'>"+transNullToBlank(getParamMemo(value.accType,accTypes))+"</td>" +
						"<td align='center'>"+transNullToBlank(value.openDate)+"</td>" +
						"<td align='center'>"+transNullToBlank(value.startDate)+"</td>"+
						"<td align='center'>"+transNullToBlank(value.endDate)+"</td>" +
						"<td align='center'>"+transNullToBlank(value.pointNo)+"</td>" +
						"<td align='center'>"+transNullToBlank(tempMainAccNo)+"</td>" +
						"<td style='border-right:none;' align='center'>"+transNullToBlank(getAccountFlag(value))+"</td></tr>";
					}
				});
				
				$("#con_cont").html(str+"</table>");
				
				$(".trbg").mouseover(function(){
					/*if($('.tr_checked').length > 0){
							$('.tr_checked').removeClass();
							$(this).addClass('tr_top1');
						}else{
							$(this).addClass('tr_checked');
						}*/
					$(this).toggleClass('tr_checked');
				});
				$(".trbg").mouseout(function(){
					$(this).toggleClass('tr_checked');
				});
				
				bindPager();
				
				//TODO add by youlijun
				if(p.getAttrWithAutoClear("querySealAccno")){
					showInfo(0);
				}
			},"json");
	}
	
	//双击事件
	$("#con_tab td").live("dblclick",function(){
		// 列数
		//var tdSeq = $(this).parent().find("td").index($(this)[0]);
		// 行号
        var trSeq = $(this).parent().parent().find("tr").index($(this).parent()[0]);  
        showInfo(trSeq);
        //accInfo = accInfoList[trSeq];
        if(isHaveInvaildParam(accInfo)){
			//alert("此账户存在已失效的参数!");
			invaildParamString="";
		}
        
	});
	
	// 控制不允许输入全角字符
	function noFullInput(obj){
		str = obj.val();
		//去除前后空格
		var str=str.replace(/(^\s+)|(\s+$)/g,"");
		//2013-11-05：为了保持统一，可以输入全角字符。不作全角字符检查
		/*if (str.length>0)
		{
		    for (var i = str.length-1; i >= 0; i--)
		    {
		        unicode=str.charCodeAt(i);
		        if (unicode>65280 && unicode<65375)
		        {
		            alert("不能输入全角字符，请输入半角字符");
		            obj.val(str.substr(0,i));
		        }
		    }
		}*/
		return str ;
		//return obj.val();
	}
	$("#ui_sci_addcombine").attr("disabled",true);
	function showInfo(index){
		$('#ui_sci_addcombine').removeAttr("disabled");
		$("#accInfoUI").accinfo("clean",$("#accInfoUI").data("accinfo"));
		accInfo = accInfoList[index];

		//将document显示
        if(p.getAttrWithAutoClear("querySealAccno")){
        	$(".frame").show();
		}
//		$('#accinfoTrue').css("min-height", document.body.scrollHeight+"px");
        $("#accInfoUI").accinfo("queryAndInitAccInfo",null,accInfo.accno);
//		$("#accInfoUI").accinfo("init",null,accInfo,true,false);
        //2013-10-29:账户信息询时，将账户信息页面中的账号与开户网点显灰色，使其不能修改。
        $("#accno").attr("disabled","disabled");
        $("#pointNo").attr("disabled","disabled");        
		document.all.accinfodiv.style.display='block';
		// 判断是否需要显示【F9 查看组合】按钮
		if(accInfo.sealCombines != undefined && accInfo.sealCombines.length > 0){
			$("#ui_sci_addcombine").show();
		}else{
			$("#ui_sci_addcombine").hide();
		}		
		document.all.accinfodiv.style.width=document.body.clientWidth;
		$('#accinfoTrue').css("min-height", document.all.accinfodiv.offsetHeight+"px");
		$('#sealcard_big').css("height","390px");
	}
	
	//text文件界面显示时将null用""替代
	function transNullToBlankByText(value){
		if (value == undefined || value == null){
			return "";
		}
		return value;
	}
	
	//获得账户状态,已销户账户状态码仍为正常，需要使用销户时间进行判断
	window.getAccountFlag = function(account){
		var accountFlag = "";
		var curDate = parent.getServerDateTime().substring(0,10);
		if(account.endDate && account.endDate.length == 10 &&  curDate >= account.endDate){
			accountFlag = "销户";
		}else{
			accountFlag = getParamMemo(account.accFlag, accFlags);
		}
		return accountFlag;
	};

	//查找参数的描述
	function getParamMemo(id, paramEntry){
		var memo="";
		for(var i=0;i<paramEntry.length;i++){
			if (id == paramEntry[i].paramValueNum){
				memo = paramEntry[i].paramMemo;
				break;
			}
		}
		
		return memo;
	}

	// 屏蔽F5 
	$.keyCodeReg(116,function(){
		window.event.keyCode=0;
		window.event.returnValue = false;
	});
	
	// 按Esc退出 
	$.keyCodeReg(27,function(){
		if ($("#sealCombinePage").length == 0  || $("#sealCombinePage").css("display")  == "none"){
			closeInfo();
		}
	});
	
	
	
	//AJAX方法取得数据并显示到打印页面上
	/*function printData(){
		//把表单的数据进行序列化
		alert("O(∩_∩)O~");
		//document.all.WebBrowser.ExecWB(7,1);
		window.open("PDF.action");
	}*/
	
	// 页脚属性设置
	function bindPager() {
		var totalPage = parseInt($("#totalPage").text()); // 总页数
		document.getElementById("first").style.color = (currentPage == 1 || totalPage <= 1) ? "#777" : "";
		document.getElementById("previous").style.color = (currentPage == 1 || totalPage <= 1) ? "#777" : "";
		document.getElementById("next").style.color = (currentPage == 0 || totalPage == currentPage) ? "#777" : "";
		document.getElementById("last").style.color = (currentPage == 0 || totalPage == currentPage) ? "#777" : "";
		if (totalPage > 0){
			$("#explortBtn").show();
//			$("#printBtn").show();
		}else{
			$("#explortBtn").hide();
			$("#printBtn").hide();
		}
	}
	
	function initView(){
		//$$.load($$.rootpath + "/js/accNameSearch.js");
		//initAccNameSearch($("#accNoInput"));
		
		$("#startTime").datepicker({
			dateFormat:'yy-mm-dd'
		});
		
		$("#endTime").datepicker({
			dateFormat:'yy-mm-dd'
		});
		initDate();
		
		//对指定字符进行屏蔽
		//$("#accNoInput").letterandnums();
		//$("#accNameInput").letterandnums();
		//$("#pointNoInput").letterandnums();
		$("#accNoInput")[0].focus();
		
		if (accFlags == undefined){
			accFlags = getAccFlagsAll();
			//accFlags = getAccFlags();
		}
		if (accTypes == undefined){
			accTypes = getAccTypesAll();
			//accTypes = getAccTypes();
		}
		for (var i in accTypes){
			$('#accTypeSel').append("<option value='"+accTypes[i].paramValueNum+"'>"+accTypes[i].paramMemo+"</option>");
		}
		
		document.getElementById("first").style.color="#777";
		document.getElementById("previous").style.color="#777";
		document.getElementById("next").style.color="#777";
		document.getElementById("last").style.color="#777";
		$("#explortBtn").hide();
		$("#printBtn").hide();
		//获取库类型的相关年限
		currentLimitYear = getSystemParamByName("CurrentDbLimitYear");
		historyLimitYear = getSystemParamByName("HistoryDbLimitYear");
	}
	if(p.getAttrWithAutoClear("querySealAccno")){//add by youlijun
		$("#startTime").val("");
		$("#endTime").val("");
		$("#accNoInput").val(p.getAttrWithAutoClear("querySealAccno"));
		$("#searchButton").click();
	}
	function initDate(){
		var starttimeDate = $.datepicker.formatDate("yy-mm-dd", new Date(parent.getServerDateTime()));
		var data = starttimeDate.split("-");
		data[2] = parseInt(data[2],10)-7;
		$("#endTime").val(starttimeDate);
		$("#startTime").val($.datepicker.formatDate("yy-mm-dd", new Date(data[0], parseInt(data[1],10)-1, data[2])));
	}
	function printSealCardImage(){
		$("#explortDivHidden").html("");
		$("#explortDivHidden").append("<iframe id='printHiddenIframe' style='display:none' ></iframe>");
		$("#explortDivHidden").append("<form id='printForm' action='accInfoPrint.jsp' target='printHiddenIframe' method='post'></form>");
		$("#printForm").submit();
	}
});